import PropTypes from 'prop-types';

const HeadPage = (props) => {
  const { title } = props;

  return (
    <head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </head>
  );
};

HeadPage.propTypes = {
  title: PropTypes.string,
};

HeadPage.defaultProps = {
  title: '',
};

export default HeadPage;
